language: python

python:
  - "3.6"
install:
  - pip3 install -e .
  - pip3 install coveralls # For coveralls.io specifically
  - pip3 install -r tests_requirements.txt
script:
  # Main tests, w/ coverage!
  - inv test --coverage
after_success:
- coveralls
